language: c

cache:
  directories:
    - $HOME/travis-cache

os: linux
dist: bionic

arch:
  - amd64
  - arm64
  - s390x
  - ppc64le

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: osx
      before_install: true

before_install:
  - sudo apt-get -yq install strace
  - dpkg -S /usr/include/stdio.h
  - apt-cache show libc6-dev || true
script: strace -f ci/arm64-segfault-demo.sh

notifications:
  email: false
